package detector

var botAgents = []string{
	"okhttp",
	"googlebot",
	"adsbot-google",
	"headlesschrome",
	"facebookexternalhit",
	"python-requests",
	"aiohttp",
	"python-httpx",
	"Python-urllib",
	"python-urllib3",
	"nessus",
	"nessus::soap",
	"nessus/190402",
	"curl",
	"bingbot",
	"bingpreview",
	"semrushbot",
	"ahrefsbot",
	"chrome-lighthouse",
	"petalbot",
	"applebot",
	"pingdom.com_bot",
	"axios",
	"yandexbot",
	"ptst",
	"adsbot-google-mobile",
	"siteauditbot",
}
