name: Daily Scrape and Commit

on:
  schedule:
    - cron: '0 15 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Run the scrape command
      run: make scrape

    - name: Commit changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Auto scrape commit $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
        
    - name: Push to master branch
      run: |
        git push origin master